### ISSUE TITLE
Localisations not respected in some fields

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-sitewidecontent-report#22]
**SS:** 3.4.1
**This module:** 2.0.1

For example, I have a localisation like so:

``` yaml
# File: mysite/lang/en.yml
en:
  BlogPost:
    SINGULARNAME: My Custom Blog Post Name
    PLURALNAME: My Custom Blog Posts Name
```

In the report I still see "BlogPost" (as an example, it's not limited to this) when I would expect to see "My Custom Blog Post Name" which is used in its place in other places throughout the CMS.
